# Generated by Django 5.0 on 2026-05-16 21:34

import django.db.models.deletion
from django.db import migrations, models


def drop_date_creation(apps, schema_editor):
    # DROP COLUMN IF EXISTS n'est pas disponible sur toutes les versions MySQL
    # on utilise un try/except pour ignorer si la colonne n'existe plus
    try:
        schema_editor.execute("ALTER TABLE avis_avis DROP COLUMN date_creation")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_add_date_creation'),
        ('demandes', '0002_alter_demande_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_date_creation, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(model_name='avis', name='date_creation'),
            ]
        ),
        migrations.AlterField(
            model_name='avis',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='demandes.demande'),
        ),
    ]
