# Generated by Django 5.0 on 2026-05-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_add_date_creation'),
        ('demandes', '0002_alter_demande_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE avis_avis DROP COLUMN IF EXISTS date_creation",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(model_name='avis', name='date_creation'),
            ]
        ),
        migrations.AlterField(
            model_name='avis',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='demandes.demande'),
        ),
    ]
