FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
COPY frontend/ .
RUN rm -rf node_modules && npm ci
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
