server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Autorise les uploads jusqu'à 10 Mo (photos de profil)
    client_max_body_size 10m;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        resolver 127.0.0.11 valid=5s;
        set $backend http://backend:8000;
        proxy_pass $backend;
        proxy_set_header Host $host;
    }

    # Proxy les fichiers media (photos uploadées) vers Django
    location /media/ {
        resolver 127.0.0.11 valid=5s;
        set $backend http://backend:8000;
        proxy_pass $backend;
        proxy_set_header Host $host;
    }
}
