# Generated by Django 6.0.4 on 2026-04-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
