# Generated by Django 5.2.14 on 2026-05-14 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prestataire',
            index=models.Index(fields=['disponible'], name='prestataire_disponi_65d904_idx'),
        ),
        migrations.AddIndex(
            model_name='prestataire',
            index=models.Index(fields=['-note_moyenne'], name='prestataire_note_mo_dc2258_idx'),
        ),
        migrations.AddIndex(
            model_name='prestataire',
            index=models.Index(fields=['quartier'], name='prestataire_quartie_24f7fc_idx'),
        ),
    ]
