# Generated by Django 5.2.14 on 2026-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0005_merge_0002_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
