# Generated by Django 6.0.4 on 2026-04-27 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('prestataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='date_intervention',
        ),
        migrations.AddField(
            model_name='demande',
            name='titre',
            field=models.CharField(default='Sans titre', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demande',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='prestataires.prestataire'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
