# Generated by Django 5.2.14 on 2026-05-14 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('prestataires', '0002_prestataire_prestataire_disponi_65d904_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['statut'], name='demandes_de_statut_72997a_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['client'], name='demandes_de_client__c7d2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['prestataire'], name='demandes_de_prestat_2418da_idx'),
        ),
    ]
