# Generated by Django 5.0 on 2026-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alter_demande_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
