# Generated by Django 5.2.14 on 2026-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demande_adresse_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='urgence',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=20),
        ),
    ]
