# Generated by Django 5.2.14 on 2026-05-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_80c251_idx',
            old_name='chat_messag_convers_idx',
        ),
    ]
